export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/profile', component: require('./components/Profile.vue').default },
    { path: '/developer', component: require('./components/Developer.vue').default },
    { path: '/users', component: require('./components/Users.vue').default },
    // { path: '/products', component: require('./components/product/Products.vue').default },
    // { path: '/product/tag', component: require('./components/product/Tag.vue').default },
    { path: '/categories', component: require('./components/auctions/Category.vue').default },
    { path: '/auctions', component: require('./components/auctions/Auction.vue').default },
    { path: '/auctionConfirms', component: require('./components/auctionConfirms/AuctionConfirm.vue').default },
    { path: '/bets', component: require('./components/auctions/AuctionBets.vue').default },
    { path: '/lots', component: require('./components/auctions/Lots.vue').default },
    { path: '/lots/:id', component: require('./components/auctions/LotItems.vue').default },
    { path: '/lot_moderation', component: require('./components/auctions/LotsModerate.vue').default },
    // { path: '/bargainings', component: require('./components/auctions/Bargaining.vue').default },
    { path: '/countries', component: require('./components/Country.vue').default },
    // { path: '/front/auctions_front', component: require('./components/front/Auctions.vue').default },
    // { path: '/front/auctions_front/:id', component: require('./components/front/Auction_one.vue').default },
    { path: '/notifications', component: require('./components/Notifications.vue').default },
    { path: '/change_users', component: require('./components/UserConfirm.vue').default },
    { path: '/feedback', component: require('./components/Feedback.vue').default },
    { path: '/messages', component: require('./components/Contacts.vue').default },
    { path: '/export_data', component: require('./components/ExportData.vue').default },
    { path: '*', component: require('./components/NotFound.vue').default }
];
